### ISSUE TITLE
manual install of CMTK into fiji.app/bin

### ISSUE THREAD

**Issue by jjeanne** [jefferis/fiji-cmtk-gui#15]
Hi Greg,

I've been using the GUI without trouble for several weeks now, but recently had to reinstall FIJI, which removed the CMTK files from fiji.app/bin. Unfortunately I cannot reinstall CMTK to this location using the FIJI plugin "Install CMTK" because the nitrc CMTK website seems to be down (and has been for several days). Is there any way to manually move my CMTK installation to fiji.app/bin? Or to install it there with a .dmg I have hanging around? Or is it best to wait for the website to come back online and download it again?

Thanks,
Jamie

**Comment by jefferis** [comment]
Hi Jamie, I think NITRC is back online now. I generally always keep my old Fiji install if I do a substantial upgrade. If you had that you could certainly copy over the contents of Fiji.app/bin. You can also use files from a CMTK install from the dmg file (on a mac). You would need to copy the contents of `/opt/local/lib/cmtk/bin/*` and the `/opt/local/bin/cmtk` and `/opt/local/bin/munger` scripts to `Fiji.app/bin/cmtk/` (untested, but should work).

**Comment by jjeanne** [comment]
Great that worked. Thanks.
